#!/usr/bin/env ruby

require 'fileutils'
require 'open-uri'

# TODO:
# - if the dir already exists, it should just do a git pull.
# - read bundles from a config file, not right out of the script.
# - pull stuff off vimscripts too.
# - convert this script to Perl?  Should be more worldly than Ruby.

VERSION = "0.1"

bundles = {
  "Plugins" => "
    git://github.com/scrooloose/nerdtree.git
    git://github.com/scrooloose/nerdcommenter.git
    git://github.com/bronson/vim-bufexplorer.git
    git://github.com/bronson/vim-closebuffer.git
    git://git.wincent.com/command-t.git
    git://github.com/vim-ruby/vim-ruby.git
# dir layout doesn't work with pathogen, not sure if it's worth using anyway
# http://tammersaleh.com/posts/the-modern-vim-config-with-pathogen#comment_348
#      git://github.com/astashov/vim-ruby-debugger.git
    git://github.com/tpope/vim-rails.git
    git://github.com/msanders/snipmate.vim.git
    git://github.com/scrooloose/snipmate-snippets.git
    git://github.com/tpope/vim-surround.git
    git://github.com/bronson/vim-taglist.git
    git://github.com/bronson/vim-indexedsearch.git
    git://github.com/bronson/vim-ruby-block-conv.git
    git://github.com/tsaleh/vim-align.git
    git://github.com/tpope/vim-endwise.git
    git://github.com/tpope/vim-repeat.git
    git://github.com/tsaleh/vim-supertab.git
    git://github.com/mikezackles/Bisect.git
    git://github.com/rson/vim-conque.git
    git://github.com/bronson/vim-scrollcolors.git
  ",
  "Syntax Files" => "
    git://github.com/bronson/vim-jquery.git
    git://github.com/tsaleh/vim-shoulda.git
    git://github.com/tpope/vim-git.git
    git://github.com/tpope/vim-cucumber.git
    git://github.com/tpope/vim-haml.git
    git://github.com/tpope/vim-markdown.git
    git://github.com/timcharper/textile.vim.git
    git://github.com/kchmck/vim-coffee-script.git
  ",
  "Color Schemes" => "
    git://github.com/tpope/vim-vividchalk.git
  ",
}


bundles_dir = File.join(File.dirname(__FILE__), "bundle")

def download(dir, url, doc)
  puts "cloning #{dir} from #{url}"
  `git clone -q #{url} #{dir}`
  version = date = ''
  FileUtils.cd(dir) do
    version = `git describe --tags 2>/dev/null`.chomp
    version = "n/a" if version == ''
    date = `git log -1 --pretty=format:%ai`.chomp
  end
  doc.printf "  - %-30s %-22s %s\n", "|#{dir}|", version, date.split(' ').first
  # FileUtils.rm_rf(File.join(dir, ".git"))
end


File.open("doc/bundles.txt", "w") do |doc|
  doc.printf "%-32s %s %32s\n\n", "*bundles.txt*", "Bundles", "Version 0.1"
  doc.puts "These are the bundles installed on your system, along with their\n" +
    "versions and release dates.  Downloaded on #{Time.now}.\n\n" +
    "A version number of 'n/a' means upstream hasn't tagged any releases.\n"
  FileUtils.cd(bundles_dir)

  puts "Trashing everything.  Look out!"
  Dir["*"].each {|d| FileUtils.rm_rf(d) }

  bundles.each do |name,val|
    doc.puts "\n\n#{name}\n#{"-" * name.length}\n\n"
    val.each_line do |line|
      url = line.gsub(/^\s*|\s*$/, '')
      next if url == '' || url[0,1] == '#'  # skip blanks and comments
      dir = url.split('/').last.gsub(/^vim-|\.git$/, '').gsub(/\.vim$/, '')
      download(dir, url, doc)
    end
  end

  doc.puts "\n"
end

puts "updating helptags..."
`vim -e -c "call pathogen#helptags()" -c q`
puts "done!"

