#!/usr/bin/env ruby

# Reads the bundles you want installed out of your $HOME/.vimrc file,
# then synchronizes .vim/bundles to match, downloading new repositories
# as needed.  It also deletes bundles that are no longer used.
#
# To specify a bundle in your .vimrc, just add a line like this:
# " --- BUNDLE: git://git.wincent.com/command-t.git

require 'fileutils'
require 'open-uri'


def document_bundle(dir, doc)
  version = date = ''
  FileUtils.cd(dir) do
    version = `git describe --tags 2>/dev/null`.chomp
    version = "n/a" if version == ''
    date = `git log -1 --pretty=format:%ai`.chomp
  end
  doc.printf "  - %-30s %-22s %s\n", "|#{dir}|", version, date.split(' ').first
end


def download(dir, url, doc)
  if test ?d, dir
    puts "updating #{dir} from #{url}"
    FileUtils.cd(dir) { `git pull` }
  else
    puts "cloning #{dir} from #{url}"
    `git clone -q #{url} #{dir}`
  end
  document_bundle(dir, doc)
end


def read_vimrc
  bundles = []
  File.open("#{ENV['HOME']}/.vimrc") do |file|
    file.each_line do |line|
      bundles.push $1 if line =~ /^"\s*-*\s*BUNDLE:\s*(\S*)/
    end
  end
  bundles
end


def update_bundles(doc)
  existing_bundles = Dir['*']
  vimrc_bundles = read_vimrc

  vimrc_bundles.each do |url|
    dir = url.split('/').last.gsub(/^vim-|\.git$/, '').gsub(/\.vim$/, '')
    download(dir, url, doc)
    existing_bundles.delete(dir)
  end

  existing_bundles.each do |dir|
    puts "Blowing away #{dir}"
    FileUtils.rm_rf(dir)
  end
end


File.open("doc/bundles.txt", "w") do |doc|
  doc.printf "%-32s %s %32s\n\n", "*bundles.txt*", "Bundles", "Version 0.1"
  doc.puts "These are the bundles installed on your system, along with their\n" +
    "versions and release dates.  Downloaded on #{Time.now}.\n\n" +
    "A version number of 'n/a' means upstream hasn't tagged any releases.\n"

  bundles_dir = File.join(File.dirname(__FILE__), "bundle")
  FileUtils.cd(bundles_dir)
  update_bundles(doc)

  doc.puts "\n"
end

puts "updating helptags..."
`vim -e -c "call pathogen#helptags()" -c q`
puts "done!"

